export const CATEGORIES = [
  { name: "All", icon: "🛍️" },
  { name: "Electronics", icon: "📺" },
  { name: "Phones & Tablets", icon: "📱" },
  { name: "Computers", icon: "💻" },
  { name: "Vehicles", icon: "🚗" },
  { name: "Property", icon: "🏠" },
  { name: "Furniture", icon: "🛋️" },
  { name: "Home Appliances", icon: "🧺" },
  { name: "Fashion", icon: "👕" },
  { name: "Beauty", icon: "💄" },
  { name: "Sports", icon: "⚽" },
  { name: "Baby Products", icon: "🍼" },
  { name: "Books", icon: "📚" },
  { name: "Agriculture", icon: "🌾" },
  { name: "Services", icon: "🛠️" },
  { name: "Jobs", icon: "💼" },
  { name: "Other", icon: "📦" },
];
